function Hd = getFilter2()
    %GETFILTER2 Returns a discrete-time filter object.

    % MATLAB Code
    % Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
    % Generated on: 28-Mar-2018 14:31:22

    % Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

    % All frequency values are in Hz.
    Fs = 8192;  % Sampling Frequency

    Fpass = 1000;        % Passband Frequency
    Fstop = 2000;        % Stopband Frequency
    Apass = 1;           % Passband Ripple (dB)
    Astop = 80;          % Stopband Attenuation (dB)
    match = 'stopband';  % Band to match exactly

    % Construct an FDESIGN object and call its BUTTER method.
    h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
    Hd = design(h, 'butter', 'MatchExactly', match);
end